/// Flutter icons Tothem
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tothem
///      fonts:
///       - asset: fonts/Tothem.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Tothem {
  Tothem._();

  static const _kFontFam = 'Tothem';
  static const String? _kFontPkg = null;

  static const IconData filePdf =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileWord =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashEmpty =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lockOpen =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_1 =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeOff =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogAlt =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_2 =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_1 =
      IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times =
      IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 =
      IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 =
      IconData(0xf019, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronLeft =
      IconData(0xf053, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight =
      IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowLeft =
      IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowRight =
      IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp =
      IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowDown =
      IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeSlash =
      IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xf075, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp =
      IconData(0xf077, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown =
      IconData(0xf078, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpen =
      IconData(0xf07c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cameraRetro =
      IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xf09c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench_1 =
      IconData(0xf0ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      IconData(0xf0ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users =
      IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs =
      IconData(0xf0c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listUl =
      IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope =
      IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docText =
      IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleLeft =
      IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleRight =
      IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleUp =
      IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleDown =
      IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderEmpty =
      IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpenEmpty =
      IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lockOpenAlt =
      IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencilSquared =
      IconData(0xf14b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduationCap =
      IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePdf2 =
      IconData(0xf1c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileWord2 =
      IconData(0xf1c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileExcel =
      IconData(0xf1c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePowerpoint =
      IconData(0xf1c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileImage =
      IconData(0xf1c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileArchive =
      IconData(0xf1c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileAudio =
      IconData(0xf1c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileVideo =
      IconData(0xf1c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileCode =
      IconData(0xf1c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperPlane =
      IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders =
      IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggleOff =
      IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggleOn =
      IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server =
      IconData(0xf233, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentingO =
      IconData(0xf27b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_1 =
      IconData(0xf394, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortarBoard =
      IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sistrix =
      IconData(0xf3ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userAlt =
      IconData(0xf406, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentDots =
      IconData(0xf4ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userEdit =
      IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chalkboard =
      IconData(0xf51b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chalkboardTeacher =
      IconData(0xf51c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
