name: tothem
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.2.2
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  const_date_time: ^1.0.2
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.5.3
  get: ^4.6.5
  dio: ^5.1.2
  device_info_plus: ^9.0.2
  image_gallery_saver: ^2.0.1
  path_provider: ^2.0.15
  timeago: ^3.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

  fonts:
    - family:  Tothem
      fonts:
      - asset: fonts/Tothem.ttf